name: Auto Assign to Test.Project

on:
  issues:
    types: [opened, labeled, unlabeled]
env:
  GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign any new issue to Test Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/deepalite6094/test/projects/1'
        
    - name: Assign issues to Test project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/deepalite6094/test/projects/1'
        column_name: 'To do'
