name: Auto Assign to Test.Project

on:
  issues:
    types: [opened, labeled, unlabeled]
env:
  ENV_SECRET: ${{ secrets.ENV_SECRET }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Echo
      run: | 
        echo ${{github.event == 'issue'}}
        echo ${{secrets.SECRET_TOKEN}}
      
    - name: Assign any new issue to Test Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: true
      with:
        project: 'https://github.com/deepalite6094/test/projects/1'
