name: Auto Assign to Test.Project

on:
  issues:
    types: [opened, labeled, unlabeled]
env:
  GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Event echo
      run: echo ${{ github.event }}
      
    - name: Assign any new issue to Test Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event == 'issue'
      with:
        project: 'https://github.com/deepalite6094/test/projects/1'
