name: Auto Assign to Test Project

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  assign_to_test_project:
    runs-on: ubuntu-latest
    name: Assign to Test Project Board
    steps:
    - name: Assign any new issue to test Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened'
      with:
        project: 'https://github.com/deepalite6094/test/projects/1'
